#!/usr/bin/env bash
set -euo pipefail

# ── build_skill.sh ───────────────────────────────────────────────────────────
# Assembles the generating-xlsforms skill from content templates + live data.
#
# Content:  scripts/skill-content/SKILL.md                → skill root
# Fetches:  umfragen.civic-data.de/llm.txt                → references/survey-methodology.md
#           umfragen.civic-data.de/llm-xlsform.txt         → references/xlsform-spec.md
#           qwacback.correlaid.org API demographics        → references/demographic-templates.md
#           formtransform release asset (FORMTRANSFORM_VERSION) → cdl-survey-types/ sub-skill
#
# Usage:
#   ./scripts/build_skill.sh                          # default output
#   ./scripts/build_skill.sh ./custom-dir             # custom output dir
#   EXTRA_QUERIES="Ehrenamt Vertrauen" ./scripts/build_skill.sh
# ─────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONTENT_DIR="$SCRIPT_DIR/skill-content"

OUT="${1:-$PROJECT_ROOT/skills/xlsform}"
REFS="$OUT/references"

LLM_METHODOLOGY_URL="https://umfragen.civic-data.de/llm-phases12-xlsform.txt"
QWAC_API="https://qwacback.correlaid.org/api"

# Sub-skill source: cdl-survey-types is generated by formtransform codegen and
# is the authoritative catalogue for the XLSForm allowlist. It is fetched from a
# formtransform release, never a branch — a registry change should never alter a
# shipped skill without a formulaid commit. Keep the version in step with the
# formtransform dependency in package.json, and update the checksum with it
# (sha256sum of the downloaded tarball): release assets can be replaced, the
# checksum makes that fail the build instead of changing the skill silently.
FORMTRANSFORM_VERSION="0.1.7"
FORMTRANSFORM_SKILL_SHA256="61aadec2d9c45dd3cc78930a67295405f009a2805271165338d742f08f3bf00c"
FORMTRANSFORM_SKILL_URL="https://github.com/CorrelAid/formtransform/releases/download/v$FORMTRANSFORM_VERSION/cdl-survey-types-$FORMTRANSFORM_VERSION.tar.gz"

# Demographic sources (specific question + study)
DEMOGRAPHIC_QUESTION_ID="z4bm7lrn7mopedd"
DEMOGRAPHIC_STUDY_ID="2z4e5jfgc6s6mwy"

# ── helpers ──────────────────────────────────────────────────────────────────

log()  { echo "  $1"; }
ok()   { echo "     ✓ $1"; }
fail() { echo "     ✗ $1"; }
warn() { echo "     ⚠ $1"; }

fetch_to_file() {
  local url="$1" dest="$2" label="$3"
  log "⬇  $label"
  local http_code
  http_code=$(curl -sS -w "%{http_code}" -o "$dest" \
    -H "User-Agent: xlsform-skill-builder/1.0" \
    --max-time 30 "$url" 2>/dev/null) || true
  if [[ "$http_code" == "200" && -s "$dest" ]]; then
    ok "$(wc -c < "$dest" | awk '{printf "%.1f KB", $1/1024}')"
    return 0
  else
    fail "HTTP $http_code — $url"
    rm -f "$dest"
    return 1
  fi
}

fetch_json() {
  local url="$1" label="$2"
  log "⬇  $label" >&2
  local body http_code tmpfile
  tmpfile=$(mktemp)
  http_code=$(curl -sS -w "%{http_code}" -o "$tmpfile" \
    -H "Accept: application/json" \
    -H "User-Agent: xlsform-skill-builder/1.0" \
    --max-time 20 "$url" 2>/dev/null) || true
  if [[ "$http_code" == "200" && -s "$tmpfile" ]]; then
    body=$(cat "$tmpfile")
    ok "$(echo "$body" | wc -c | awk '{printf "%.1f KB", $1/1024}')" >&2
    rm -f "$tmpfile"
    echo "$body"
  else
    fail "HTTP $http_code" >&2
    rm -f "$tmpfile"
    echo ""
  fi
}

# URL-encode a string
urlencode() {
  python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))" "$1" 2>/dev/null \
    || echo "${1// /+}"
}

# ── clean & create dirs ─────────────────────────────────────────────────────

echo ""
echo "🔧 Building xlsform skill → $OUT"
echo ""

[[ -d "$OUT" ]] && rm -rf "$OUT"
mkdir -p "$REFS"

# ── 1. Copy SKILL.md ────────────────────────────────────────────────────────

echo "📝 SKILL.md"
if [[ -f "$CONTENT_DIR/SKILL.md" ]]; then
  cp "$CONTENT_DIR/SKILL.md" "$OUT/SKILL.md"
  ok "copied from $CONTENT_DIR/SKILL.md"
else
  fail "SKILL.md template not found at $CONTENT_DIR/SKILL.md"
  exit 1
fi

if [[ -f "$CONTENT_DIR/generate-instructions.md" ]]; then
  cp "$CONTENT_DIR/generate-instructions.md" "$OUT/generate-instructions.md"
  ok "generate-instructions.md copied"
else
  warn "generate-instructions.md not found at $CONTENT_DIR/generate-instructions.md"
fi

# ── 2. Vendor cdl-survey-types sub-skill from formtransform ─────────────────

echo ""
echo "🧩 Vendoring cdl-survey-types sub-skill"

SUB_SKILL_DST="$OUT/cdl-survey-types"
SUB_SKILL_TGZ=$(mktemp)
trap 'rm -f "$SUB_SKILL_TGZ"' EXIT

if ! curl -sSfL --max-time 60 -o "$SUB_SKILL_TGZ" "$FORMTRANSFORM_SKILL_URL"; then
  fail "Download failed: $FORMTRANSFORM_SKILL_URL"
  exit 1
fi

actual_sha=$(sha256sum "$SUB_SKILL_TGZ" | cut -d' ' -f1)
if [[ "$actual_sha" != "$FORMTRANSFORM_SKILL_SHA256" ]]; then
  fail "Checksum mismatch for cdl-survey-types $FORMTRANSFORM_VERSION"
  fail "expected $FORMTRANSFORM_SKILL_SHA256"
  fail "got      $actual_sha"
  exit 1
fi

rm -rf "$SUB_SKILL_DST"
mkdir -p "$SUB_SKILL_DST"
tar -xzf "$SUB_SKILL_TGZ" --strip-components=1 -C "$SUB_SKILL_DST"

# Sanity check the vendor — a shipped skill without its type reference is worse
# than a stale one, because the model falls back on generic XLSForm knowledge.
for f in SKILL.md references/question-types.md references/xlsform-syntax.md; do
  if [[ ! -s "$SUB_SKILL_DST/$f" ]]; then
    fail "Vendored sub-skill missing or empty: $f"
    exit 1
  fi
done

ok "vendored formtransform v$FORMTRANSFORM_VERSION (sha256 verified)"
ok "$(find "$SUB_SKILL_DST" -type f | wc -l) files → $SUB_SKILL_DST"

# ── 3. Fetch methodology references ─────────────────────────────────────────

echo ""
echo "📚 Fetching methodology references"

# 2a. Survey methodology + XLSForm spec (phases 1–2 with XLSForm examples)
if ! fetch_to_file "$LLM_METHODOLOGY_URL" "$REFS/survey-methodology.md" "llm-phases12-xlsform.txt"; then
  cat > "$REFS/survey-methodology.md" << 'FALLBACK'
# Survey Methodology (fetch failed at build time)

Reference data unavailable. Apply general survey methodology principles:
- Start with easy questions; move sensitive topics to later
- Use validated instruments when available (search qwac first)
- Collect numeric values as numbers, not category intervals
- Include DSGVO consent statement when collecting personal data
- Keep surveys as short as possible; every question must serve a research question
- Pre-test before deployment
FALLBACK
  warn "fallback written"
fi

# 2b. Strip the generic XLSForm specification and answer-type catalogue.
# The allowlist now lives in the vendored cdl-survey-types sub-skill; this
# file should only carry the survey-methodology content that exists nowhere
# upstream. Two cut points to handle upstream reshuffles:
#   1. Old layout: keep between "# XLSForm-Dokumentation" and "# Fragen formulieren"
#   2. New layout: drop everything from "## Was ist eine XLSForm?" onward
strip_done=false
old_start=$(grep -n '^# XLSForm-Dokumentation$' "$REFS/survey-methodology.md" 2>/dev/null | head -1 | cut -d: -f1 || true)
old_end=$(grep -n '^# Fragen formulieren$'   "$REFS/survey-methodology.md" 2>/dev/null | head -1 | cut -d: -f1 || true)
if [[ -n "$old_start" && -n "$old_end" && "$old_end" -gt "$old_start" ]]; then
  sed -i "${old_start},$((old_end - 1))d" "$REFS/survey-methodology.md"
  ok "stripped XLSForm-Dokumentation + Antworttypen (lines $old_start..$((old_end - 1)))"
  strip_done=true
fi
new_start=$(grep -n '^## Was ist eine XLSForm?$' "$REFS/survey-methodology.md" 2>/dev/null | head -1 | cut -d: -f1 || true)
if [[ "$strip_done" == "false" && -n "$new_start" ]]; then
  total=$(wc -l < "$REFS/survey-methodology.md")
  sed -i "${new_start},\$d" "$REFS/survey-methodology.md"
  ok "stripped new-layout XLSForm spec from line $new_start to $total"
  strip_done=true
fi
if [[ "$strip_done" == "false" ]]; then
  warn "no strip markers matched; survey-methodology.md shipped unchanged"
  warn "if the upstream layout changed again, update scripts/build_skill.sh"
fi

# ── 4. Fetch demographic templates from qwac ────────────────────────────────

echo ""
echo "🔍 Fetching demographics from qwac"

DEMO_FILE="$REFS/demographic-templates.md"
cp "$CONTENT_DIR/demographic-header.md" "$DEMO_FILE"

FOUND_RESULTS=false
# Any fetch that fails makes this build's copy incomplete (see the end of 4).
ALL_FETCHED=true

# 4a. Fetch single demographic question
q_result=$(fetch_json "$QWAC_API/questions/$DEMOGRAPHIC_QUESTION_ID" "Question: $DEMOGRAPHIC_QUESTION_ID")
if [[ -n "$q_result" && "$q_result" != "null" ]]; then
  printf '\n## Question: %s\n\n```json\n%s\n```\n' "$DEMOGRAPHIC_QUESTION_ID" "$q_result" >> "$DEMO_FILE"
  q_xlsform=$(fetch_json "$QWAC_API/questions/$DEMOGRAPHIC_QUESTION_ID/xlsform" "  → XLSForm: $DEMOGRAPHIC_QUESTION_ID")
  if [[ -n "$q_xlsform" && "$q_xlsform" != "null" ]]; then
    printf '\n### XLSForm\n\n```json\n%s\n```\n' "$q_xlsform" >> "$DEMO_FILE"
  fi
  FOUND_RESULTS=true
else
  ALL_FETCHED=false
fi
sleep 0.3

# 4b. Fetch all questions from demographic study + XLSForm export
# Study metadata is a plain PocketBase record; only the questions and xlsform
# sub-routes exist under /studies.
meta=$(fetch_json "$QWAC_API/collections/studies/records/$DEMOGRAPHIC_STUDY_ID" "Study: $DEMOGRAPHIC_STUDY_ID")
if [[ -n "$meta" && "$meta" != "null" ]]; then
  title=$(echo "$meta" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('title',''))" 2>/dev/null || echo "$DEMOGRAPHIC_STUDY_ID")
  printf '\n## Study: %s (id: %s)\n\n```json\n%s\n```\n' "$title" "$DEMOGRAPHIC_STUDY_ID" "${meta:0:3000}" >> "$DEMO_FILE"
  FOUND_RESULTS=true
else
  ALL_FETCHED=false
fi

study_qs=$(fetch_json "$QWAC_API/studies/$DEMOGRAPHIC_STUDY_ID/questions?perPage=100" "  → Questions")
if [[ -n "$study_qs" && "$study_qs" != "null" ]]; then
  printf '\n### Questions\n\n```json\n%s\n```\n' "${study_qs:0:15000}" >> "$DEMO_FILE"
else
  ALL_FETCHED=false
fi

xlsform=$(fetch_json "$QWAC_API/studies/$DEMOGRAPHIC_STUDY_ID/xlsform" "  → XLSForm export")
if [[ -n "$xlsform" && "$xlsform" != "null" ]]; then
  printf '\n### XLSForm Export\n\n```json\n%s\n```\n' "${xlsform:0:10000}" >> "$DEMO_FILE"
else
  ALL_FETCHED=false
fi

# When qwac is down, don't replace a good copy with a partial one: the
# pre-commit hook runs this build on every commit, and the result is staged.
# Keep the committed version and say so.
DEMO_REL="${DEMO_FILE#"$PROJECT_ROOT"/}"
if [[ "$ALL_FETCHED" == "false" ]] && git -C "$PROJECT_ROOT" cat-file -e "HEAD:$DEMO_REL" 2>/dev/null; then
  git -C "$PROJECT_ROOT" show "HEAD:$DEMO_REL" > "$DEMO_FILE"
  warn "qwac unreachable or incomplete: kept the committed $DEMO_REL"
elif [[ "$FOUND_RESULTS" == "false" ]]; then
  cat "$CONTENT_DIR/demographic-fallback.md" >> "$DEMO_FILE"
fi

# ── 5. Embed references into generate-instructions.md ───────────────────────
# generate-instructions.md is the web app's whole system prompt, sent on every
# tool step and repair (#15). It gets the type allowlist it tells the model to
# follow, and only the questionnaire-design chapters of the methodology.
# references/ keeps the full text for the Claude skill.

echo ""
echo "📎 Embedding references into generate-instructions.md"

GEN_INSTR="$OUT/generate-instructions.md"
GEN_CHAPTERS=(
  "Forschungsfragen formulieren"
  "Messtheorie & Konstrukte"
  "Operationalisierung"
  "Fragebogenaufbau"
  "Fragen formulieren"
  "Antworttypen"
)

for f in references/question-types.md references/xlsform-syntax.md; do
  printf '\n\n---\n\n' >> "$GEN_INSTR"
  cat "$SUB_SKILL_DST/$f" >> "$GEN_INSTR"
done
ok "cdl-survey-types question types + syntax appended"

if [[ -f "$REFS/survey-methodology.md" ]]; then
  printf '\n\n---\n\n## Survey Methodology\n\n' >> "$GEN_INSTR"
  # The llm.txt joins page bodies with "---" in table-of-contents order and
  # the pages carry no titles of their own, so pair them with the TOC entries.
  # If the two don't line up, embed everything rather than guess.
  python3 - "$REFS/survey-methodology.md" "${GEN_CHAPTERS[@]}" >> "$GEN_INSTR" <<'PY' || { cat "$REFS/survey-methodology.md" >> "$GEN_INSTR"; warn "chapter filter failed; full methodology embedded"; }
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
keep = sys.argv[2:]
parts = [p.strip() for p in text.split("\n\n---\n\n")]
titles = re.findall(r"^ {3}- (.+)$", parts[0], re.M)
pages = parts[1:]
if len(titles) != len(pages) or not set(keep) <= set(titles):
    sys.exit(f"{len(titles)} TOC entries, {len(pages)} pages, missing: {set(keep) - set(titles)}")
out = [f"### Kapitel: {t}\n\n{p}" for t, p in zip(titles, pages) if t in keep and p]
print("\n\n---\n\n".join(out))
PY
  ok "methodology: ${#GEN_CHAPTERS[@]} questionnaire-design chapters appended"
fi

# ── 6. Package as zip ──────────────────────────────────────────────────────

echo ""
echo "📦 Packaging"

SKILLS_DIR="$(dirname "$OUT")"
SKILL_NAME="$(basename "$OUT")"
ZIP_PATH="$SKILLS_DIR/${SKILL_NAME}.zip"

# Version line in SKILL.md, so users can compare what they have installed with
# the repo (README → Updating the skill). It hashes the skill's content, not the
# build time: rebuilding unchanged content gives the same version.
CONTENT_HASH=$(cd "$OUT" && find . -type f ! -name SKILL.md -print0 | LC_ALL=C sort -z \
  | xargs -0 sha256sum | cat - SKILL.md | sha256sum | cut -c1-8)
SKILL_VERSION="$CONTENT_HASH (formtransform v$FORMTRANSFORM_VERSION)"
awk -v v="$SKILL_VERSION" '
  !done && /^# / { print; print ""; print "Skill version: " v; done = 1; next }
  { print }' "$OUT/SKILL.md" > "$OUT/SKILL.md.tmp" && mv "$OUT/SKILL.md.tmp" "$OUT/SKILL.md"
ok "version $SKILL_VERSION"

# Reproducible zip: fixed timestamps, sorted entries, no extra attributes.
# Unchanged content gives a byte-identical zip, so a rebuild only shows up in
# git when the skill really changed.
find "$OUT" -exec touch -h -d '2000-01-01T00:00:00Z' {} +
rm -f "$ZIP_PATH"
(cd "$SKILLS_DIR" && find "$SKILL_NAME" | LC_ALL=C sort | zip -qX "$ZIP_PATH" -@)
ok "$ZIP_PATH"

# ── 7. Stage outputs ────────────────────────────────────────────────────────

git -C "$PROJECT_ROOT" add "$OUT" "$ZIP_PATH" 2>/dev/null || true

# ── Summary ─────────────────────────────────────────────────────────────────

echo ""
TOTAL_SIZE=$(find "$OUT" -type f -exec cat {} + | wc -c | awk '{printf "%.0f", $1/1024}')
FILE_COUNT=$(find "$OUT" -type f | wc -l)
echo "✅ $FILE_COUNT files, ${TOTAL_SIZE} KB → $ZIP_PATH"
echo ""
